version: "3.8"
services:
  nextjs-backend-1:
    container_name: nextjs-backend-1
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - nextjs-db-1
    networks:
      - app-network
    restart: always
    volumes:
      - app-public:/var/www/html/public

  nextjs-nginx-1:
    container_name: nextjs-nginx-1
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - app-public:/var/www/html/public:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - nextjs-backend-1
    networks:
      - app-network
    restart: always

  nextjs-db-1:
    container_name: nextjs-db-1
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: nextjs
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    restart: always

volumes:
  dbdata:
  app-public:

networks:
  app-network:
    driver: bridge
