name: Deploy to EC2 (Docker Compose)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /var/www/order-management
            git pull origin main
            echo "$ENV_PRODUCTION" > .env.production
            
            # ディスク容量確保
            docker system prune -af --volumes
            
            # コンテナを完全に停止
            docker-compose -f docker-compose.prod.yml down
            
            # ビルドと起動（--force-recreateでコンテナ再作成を強制）
            docker-compose -f docker-compose.prod.yml up -d --build --force-recreate
            
            # データベース準備待機
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 bash -c "
            echo 'Waiting for database connection...'
            for i in {1..30}; do
              php -r \"try { new PDO('mysql:host=nextjs-db-1;dbname=nextjs', 'root', 'root'); echo 'Database connected!'; exit(0); } catch(Exception \$e) { echo '.'; sleep(2); }\"
              if [ \$? -eq 0 ]; then
                break
              fi
            done
            "
            
            # キャッシュをクリア
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan route:clear
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan config:clear
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan optimize:clear
            
            # マイグレーションとシーディングを実行
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan migrate --force
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan db:seed --force
            
            # 残りのアプリケーションセットアップ
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan optimize
            docker-compose -f docker-compose.prod.yml exec -T nextjs-backend-1 php artisan cache:clear
          EOF
        env:
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
